apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sddcluster
  region: ap-south-1

nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: Omos
  - name: ng2
    instanceType: t3.small
    desiredCapacity: 1
    ssh:
      publicKeyName: Omos                       
