apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 80
  selector:
    app: prometheus
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: prometheus
        tier: backend
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
        - name: pro-volume
          mountPath: /etc/prometheus
        - name: all-info
          mountPath: /prometheus
        ports:
        - containerPort: 80
          name: drupal
      volumes:
        - name: pro-volume
          configMap:
            name: config-pro
        - name: all-info
          persistentVolumeClaim:
            claimName: efs-drupal
